### ISSUE TITLE
Link to specific page sections?

### ISSUE THREAD

**Issue by jbenet** [starboard-ventures/filecoin-network-health-dashboard#2]
Would be nice to be able to link to specific navigation sections (specific graphs works already)

like, clicking on Gas Usage on the left bar should add an anchor (`#gas-usage`) to the URL bar to be able to link to that section specifically. 

![Screen Shot 2023-04-27 at 17 54 50](https://user-images.githubusercontent.com/138401/234951054-24729ba9-b074-4553-aa44-8d41fd9da55a.png)

**Comment by jbenet** [comment]
Note: this already works for linking to specific graphs, like clicking the "copy-link" item copies the following URL, which has anchors for the graph itself https://dashboard.starboard.ventures/transactions-usage#gas-usage-by-methods 

![Screen Shot 2023-04-27 at 17 56 16](https://user-images.githubusercontent.com/138401/234951392-7f04f128-b479-4b40-a771-30697f1434c0.png)

**Comment by sylvanzhang** [comment]
Hi Juan,

The feature is live now. Thanks for your feedback!

![image](https://github.com/starboard-ventures/filecoin-network-health-dashboard/assets/79552241/5eec03f4-3106-4f1e-b5d4-9f032f7bd6e9)
